name: py39
channels:
    - miniconda
    - conda-forge
    - defaults
dependencies:
    - astroid=2.9.0
    - attrs=21.4.0
    - autopep8=1.5.6
    - backcall=0.2.0
    - blas=1.0
    - bleach=4.1.0
    - bottleneck=1.3.2
    - branca=0.4.2
    - ca-certificates=2021.10.8
    - certifi=2021.10.8
    - debugpy=1.5.1
    - decorator=5.1.1
    - defusedxml=0.7.1
    - entrypoints=0.3
    - flake8=3.9.0
    - future=0.18.2
    - geos=3.10.2
    - importlib-metadata=4.8.2
    - importlib_resources=5.4.0
    - intel-openmp=2021.4.0
    - ipydatawidgets=4.2.0
    - ipykernel=6.4.1
    - ipyleaflet=0.15.0
    - ipython=7.31.1
    - ipython_genutils=0.2.0
    - ipywidgets=7.6.5
    - isort=5.9.3
    - jedi=0.17.2
    - jinja2=3.0.3
    - jsonschema=4.4.0
    - jupyter_client=7.1.2
    - jupyter_core=4.9.1
    - jupyterlab_widgets=1.0.2
    - lazy-object-proxy=1.6.0
    - libffi=3.3
    - libsodium=1.0.18
    - markupsafe=2.1.0
    - matplotlib-inline=0.1.2
    - matplotlib=3.5.1
    - mccabe=0.6.1
    - mistune=0.8.4
    - mkl=2021.4.0
    - mkl-service=2.4.0
    - mkl_fft=1.3.1
    - mkl_random=1.2.2
    - multipledispatch=0.6.0
    - nbconvert=5.6.1
    - nbformat=5.2.0
    - nest-asyncio=1.5.1
    - notebook=5.7.11
    - numexpr=2.8.1
    - numpy=1.21.2
    - numpy-base=1.21.2
    - openssl=1.1.1l
    - packaging=21.3
    - pandas=1.3.5
    - pandocfilters=1.5.0
    - parso=0.7.0
    - pexpect=4.8.0
    - pickleshare=0.7.5
    - pip=21.2.4
    - platformdirs=2.4.0
    - plotly=5.3.1
    - pluggy=1.0.0
    - prometheus_client=0.13.1
    - prompt-toolkit=3.0.20
    - ptyprocess=0.7.0
    - pycodestyle=2.6.0
    - pydocstyle=6.1.1
    - pyflakes=2.2.0
    - pygments=2.11.2
    - pylint=2.12.2
    - pyparsing=3.0.4
    - pyrsistent=0.18.1
    - python=3.9.7
    - python-dateutil=2.8.2
    - python-jsonrpc-server=0.4.0
    - python-language-server=0.36.2
    - python_abi=3.9
    - pythreejs=2.3.0
    - pytz=2021.3
    - pyyaml=6.0
    - pyzmq=22.3.0
    - rope=0.22.0
    - send2trash=1.8.0
    - setuptools=58.0.4
    - shapely=1.8.0
    - simplejson=3.17.6
    - six=1.16.0
    - snowballstemmer=2.2.0
    - sqlite=3.37.2
    - tenacity=8.0.1
    - terminado=0.13.3
    - testpath=0.6.0
    - tk=8.6.11
    - toml=0.10.2
    - tornado=6.1
    - traitlets=5.1.1
    - traittypes=0.2.1
    - typing-extensions=3.10.0.2
    - typing_extensions=3.10.0.2
    - tzdata=2021e
    - ujson=4.2.0
    - wcwidth=0.2.5
    - webencodings=0.5.1
    - wheel=0.37.1
    - widgetsnbextension=3.5.2
    - wrapt=1.13.3
    - xyzservices=2022.3.0
    - xz=5.2.5
    - yaml=0.2.5
    - yapf=0.31.0
    - zeromq=4.3.4
    - zipp=3.7.0
    - zlib=1.2.11
    - mlflow=1.24.0
    - pytorch=1.11.0
    - torchvision=0.12.0
    - tensorflow=2.7.0